// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: src/proto/fileservice.proto

package fileservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteAddress string `protobuf:"bytes,1,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_fileservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_fileservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_fileservice_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

type HandshakeResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionUuid string `protobuf:"bytes,2,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
}

func (x *HandshakeResponce) Reset() {
	*x = HandshakeResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_fileservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponce) ProtoMessage() {}

func (x *HandshakeResponce) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_fileservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponce.ProtoReflect.Descriptor instead.
func (*HandshakeResponce) Descriptor() ([]byte, []int) {
	return file_src_proto_fileservice_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponce) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

type FileStreamingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionUuid    string `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
	LastFrame      bool   `protobuf:"varint,2,opt,name=last_frame,json=lastFrame,proto3" json:"last_frame,omitempty"`
	StreamingFrame []byte `protobuf:"bytes,3,opt,name=streaming_frame,json=streamingFrame,proto3" json:"streaming_frame,omitempty"`
}

func (x *FileStreamingRequest) Reset() {
	*x = FileStreamingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_fileservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStreamingRequest) ProtoMessage() {}

func (x *FileStreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_fileservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStreamingRequest.ProtoReflect.Descriptor instead.
func (*FileStreamingRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_fileservice_proto_rawDescGZIP(), []int{2}
}

func (x *FileStreamingRequest) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *FileStreamingRequest) GetLastFrame() bool {
	if x != nil {
		return x.LastFrame
	}
	return false
}

func (x *FileStreamingRequest) GetStreamingFrame() []byte {
	if x != nil {
		return x.StreamingFrame
	}
	return nil
}

type FileStreamingResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FileStreamingResponce) Reset() {
	*x = FileStreamingResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_proto_fileservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStreamingResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStreamingResponce) ProtoMessage() {}

func (x *FileStreamingResponce) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_fileservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStreamingResponce.ProtoReflect.Descriptor instead.
func (*FileStreamingResponce) Descriptor() ([]byte, []int) {
	return file_src_proto_fileservice_proto_rawDescGZIP(), []int{3}
}

func (x *FileStreamingResponce) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FileStreamingResponce) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_src_proto_fileservice_proto protoreflect.FileDescriptor

var file_src_proto_fileservice_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x10, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x36, 0x0a, 0x11, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x14, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x15, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x11, 0x5a, 0x0f, 0x73, 0x72,
	0x63, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_fileservice_proto_rawDescOnce sync.Once
	file_src_proto_fileservice_proto_rawDescData = file_src_proto_fileservice_proto_rawDesc
)

func file_src_proto_fileservice_proto_rawDescGZIP() []byte {
	file_src_proto_fileservice_proto_rawDescOnce.Do(func() {
		file_src_proto_fileservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_fileservice_proto_rawDescData)
	})
	return file_src_proto_fileservice_proto_rawDescData
}

var file_src_proto_fileservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_src_proto_fileservice_proto_goTypes = []interface{}{
	(*HandshakeRequest)(nil),      // 0: proto.HandshakeRequest
	(*HandshakeResponce)(nil),     // 1: proto.HandshakeResponce
	(*FileStreamingRequest)(nil),  // 2: proto.FileStreamingRequest
	(*FileStreamingResponce)(nil), // 3: proto.FileStreamingResponce
}
var file_src_proto_fileservice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_fileservice_proto_init() }
func file_src_proto_fileservice_proto_init() {
	if File_src_proto_fileservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_proto_fileservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_fileservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_fileservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileStreamingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_proto_fileservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileStreamingResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_fileservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_proto_fileservice_proto_goTypes,
		DependencyIndexes: file_src_proto_fileservice_proto_depIdxs,
		MessageInfos:      file_src_proto_fileservice_proto_msgTypes,
	}.Build()
	File_src_proto_fileservice_proto = out.File
	file_src_proto_fileservice_proto_rawDesc = nil
	file_src_proto_fileservice_proto_goTypes = nil
	file_src_proto_fileservice_proto_depIdxs = nil
}
